#ticker_list.py
# S&P 500 構成銘柄リスト
# 注記: S&P 500の構成銘柄は頻繁に入れ替わるため、このリストは特定の時点の代表的な銘柄を含んでおり、
# 最新の全500銘柄ではない可能性があります。

sp500_list = [
    {"code": "A", "name": "Agilent Technologies, Inc."},
    {"code": "AAPL", "name": "Apple Inc."},
    {"code": "ABBV", "name": "AbbVie Inc."},
    {"code": "ABNB", "name": "Airbnb, Inc."},
    {"code": "ABT", "name": "Abbott Laboratories"},
    {"code": "ACGL", "name": "Arch Capital Group Ltd."},
    {"code": "ACN", "name": "Accenture plc"},
    {"code": "ADBE", "name": "Adobe Inc."},
    {"code": "ADI", "name": "Analog Devices, Inc."},
    {"code": "ADM", "name": "Archer-Daniels-Midland Company"},
    {"code": "ADP", "name": "Automatic Data Processing, Inc."},
    {"code": "ADSK", "name": "Autodesk, Inc."},
    {"code": "AEE", "name": "Ameren Corporation"},
    {"code": "AEP", "name": "American Electric Power Company, Inc."},
    {"code": "AES", "name": "The AES Corporation"},
    {"code": "AFL", "name": "Aflac Incorporated"},
    {"code": "AIG", "name": "American International Group, Inc."},
    {"code": "AIZ", "name": "Assurant, Inc."},
    {"code": "AJG", "name": "Arthur J. Gallagher & Co."},
    {"code": "AKAM", "name": "Akamai Technologies, Inc."},
    {"code": "ALB", "name": "Albemarle Corporation"},
    {"code": "ALGN", "name": "Align Technology, Inc."},
    {"code": "ALL", "name": "The Allstate Corporation"},
    {"code": "ALLE", "name": "Allegion plc"},
    {"code": "AMAT", "name": "Applied Materials, Inc."},
    {"code": "AMCR", "name": "Amcor plc"},
    {"code": "AMD", "name": "Advanced Micro Devices, Inc."},
    {"code": "AME", "name": "AMETEK, Inc."},
    {"code": "AMGN", "name": "Amgen Inc."},
    {"code": "AMP", "name": "Ameriprise Financial, Inc."},
    {"code": "AMT", "name": "American Tower Corporation"},
    {"code": "AMZN", "name": "Amazon.com, Inc."},
    {"code": "ANET", "name": "Arista Networks, Inc."},
    {"code": "AON", "name": "Aon plc"},
    {"code": "AOS", "name": "A. O. Smith Corporation"},
    {"code": "APA", "name": "APA Corporation"},
    {"code": "APD", "name": "Air Products and Chemicals, Inc."},
    {"code": "APH", "name": "Amphenol Corporation"},
    {"code": "APO", "name": "Apollo Global Management, Inc."},
    {"code": "APP", "name": "AppLovin Corporation"},
    {"code": "APTV", "name": "Aptiv plc"},
    {"code": "ARE", "name": "Alexandria Real Estate Equities, Inc."},
    {"code": "ATO", "name": "Atmos Energy Corporation"},
    {"code": "AVB", "name": "AvalonBay Communities, Inc."},
    {"code": "AVGO", "name": "Broadcom Inc."},
    {"code": "AVY", "name": "Avery Dennison Corporation"},
    {"code": "AWK", "name": "American Water Works Company, Inc."},
    {"code": "AXON", "name": "Axon Enterprise, Inc."},
    {"code": "AXP", "name": "American Express Company"},
    {"code": "AZO", "name": "AutoZone, Inc."},
    {"code": "BA", "name": "The Boeing Company"},
    {"code": "BAC", "name": "Bank of America Corporation"},
    {"code": "BALL", "name": "Ball Corporation"},
    {"code": "BAX", "name": "Baxter International Inc."},
    {"code": "BBWI", "name": "Bath & Body Works, Inc."},
    {"code": "BBY", "name": "Best Buy Co., Inc."},
    {"code": "BDX", "name": "Becton, Dickinson and Company"},
    {"code": "BEN", "name": "Franklin Resources, Inc."},
    {"code": "BF.B", "name": "Brown-Forman Corporation (Class B)"},
    {"code": "BG", "name": "Bunge Global SA"},
    {"code": "BIIB", "name": "Biogen Inc."},
    {"code": "BIO", "name": "Bio-Rad Laboratories, Inc."},
    {"code": "BKR", "name": "Baker Hughes Company"},
    {"code": "BLK", "name": "BlackRock, Inc."},
    {"code": "BMS", "name": "Bemis Company, Inc. (Acquired)"}, # Placeholder for a historical entry
    {"code": "BMY", "name": "Bristol-Myers Squibb Company"},
    {"code": "BR", "name": "Broadridge Financial Solutions, Inc."},
    {"code": "BRK.B", "name": "Berkshire Hathaway Inc. (Class B)"},
    {"code": "BSX", "name": "Boston Scientific Corporation"},
    {"code": "BWA", "name": "BorgWarner Inc."},
    {"code": "BXP", "name": "Boston Properties, Inc."},
    {"code": "C", "name": "Citigroup Inc."},
    {"code": "CAG", "name": "Conagra Brands, Inc."},
    {"code": "CAH", "name": "Cardinal Health, Inc."},
    {"code": "CAT", "name": "Caterpillar Inc."},
    {"code": "CB", "name": "Chubb Limited"},
    {"code": "CBOE", "name": "Cboe Global Markets, Inc."},
    {"code": "CBRE", "name": "CBRE Group, Inc."},
    {"code": "CCI", "name": "Crown Castle International Corp."},
    {"code": "CCL", "name": "Carnival Corporation & plc (Historical)"}, # Placeholder for a historical entry
    {"code": "CDAY", "name": "Ceridian HCM Holding Inc."},
    {"code": "CDNS", "name": "Cadence Design Systems, Inc."},
    {"code": "CDW", "name": "CDW Corporation"},
    {"code": "CEG", "name": "Constellation Energy Corporation"},
    {"code": "CF", "name": "CF Industries Holdings, Inc."},
    {"code": "CHTR", "name": "Charter Communications, Inc."},
    {"code": "CI", "name": "The Cigna Group"},
    {"code": "CINF", "name": "Cincinnati Financial Corporation"},
    {"code": "CL", "name": "Colgate-Palmolive Company"},
    {"code": "CLX", "name": "The Clorox Company"},
    {"code": "CMCSA", "name": "Comcast Corporation"},
    {"code": "CME", "name": "CME Group Inc."},
    {"code": "CMG", "name": "Chipotle Mexican Grill, Inc."},
    {"code": "CNP", "name": "CenterPoint Energy, Inc."},
    {"code": "COF", "name": "Capital One Financial Corporation"},
    {"code": "COP", "name": "ConocoPhillips"},
    {"code": "COST", "name": "Costco Wholesale Corporation"},
    {"code": "CPRT", "name": "Copart, Inc."},
    {"code": "CSCO", "name": "Cisco Systems, Inc."},
    {"code": "CSX", "name": "CSX Corporation"},
    {"code": "CTAS", "name": "Cintas Corporation"},
    {"code": "CTLT", "name": "Catalent, Inc."},
    {"code": "CTSH", "name": "Cognizant Technology Solutions Corporation"},
    {"code": "CVS", "name": "CVS Health Corporation"},
    {"code": "CVX", "name": "Chevron Corporation"},
    {"code": "CZR", "name": "Caesars Entertainment, Inc."},
    {"code": "D", "name": "Dominion Energy, Inc."},
    {"code": "DAL", "name": "Delta Air Lines, Inc."},
    {"code": "DD", "name": "DuPont de Nemours, Inc."},
    {"code": "DE", "name": "Deere & Company"},
    {"code": "DFS", "name": "Discover Financial Services"},
    {"code": "DG", "name": "Dollar General Corporation"},
    {"code": "DHR", "name": "Danaher Corporation"},
    {"code": "DIS", "name": "The Walt Disney Company"},
    {"code": "DISH", "name": "DISH Network Corporation (Historical)"},
    {"code": "DLR", "name": "Digital Realty Trust, Inc."},
    {"code": "DOV", "name": "Dover Corporation"},
    {"code": "DOW", "name": "Dow Inc."},
    {"code": "DPZ", "name": "Domino's Pizza, Inc."},
    {"code": "DRI", "name": "Darden Restaurants, Inc."},
    {"code": "DTE", "name": "DTE Energy Company"},
    {"code": "DUK", "name": "Duke Energy Corporation"},
    {"code": "DXCM", "name": "DexCom, Inc."},
    {"code": "EA", "name": "Electronic Arts Inc."},
    {"code": "EBAY", "name": "eBay Inc."},
    {"code": "ECL", "name": "Ecolab Inc."},
    {"code": "ED", "name": "Consolidated Edison, Inc."},
    {"code": "EE", "name": "Enphase Energy, Inc."}, # Corrected entry for ENPH
    {"code": "EIX", "name": "Edison International"},
    {"code": "EL", "name": "The Estée Lauder Companies Inc."},
    {"code": "EMR", "name": "Emerson Electric Co."},
    {"code": "ENPH", "name": "Enphase Energy, Inc."},
    {"code": "EOG", "name": "EOG Resources, Inc."},
    {"code": "EQIX", "name": "Equinix, Inc."},
    {"code": "ES", "name": "Eversource Energy"},
    {"code": "ETN", "name": "Eaton Corporation plc"},
    {"code": "ETR", "name": "Entergy Corporation"},
    {"code": "EVRG", "name": "Evergy, Inc."},
    {"code": "F", "name": "Ford Motor Company"},
    {"code": "FANG", "name": "Diamondback Energy, Inc."},
    {"code": "FAST", "name": "Fastenal Company"},
    {"code": "FCX", "name": "Freeport-McMoRan Inc."},
    {"code": "FDS", "name": "FactSet Research Systems Inc."},
    {"code": "FDX", "name": "FedEx Corporation"},
    {"code": "FE", "name": "FirstEnergy Corp."},
    {"code": "FFIV", "name": "F5, Inc."},
    {"code": "FIS", "name": "Fidelity National Information Services, Inc."},
    {"code": "FITB", "name": "Fifth Third Bancorp"},
    {"code": "FMC", "name": "FMC Corporation"},
    {"code": "FTI", "name": "TechnipFMC plc"},
    {"code": "FTNT", "name": "Fortinet, Inc."},
    {"code": "GD", "name": "General Dynamics Corporation"},
    {"code": "GE", "name": "General Electric Company"},
    {"code": "GILD", "name": "Gilead Sciences, Inc."},
    {"code": "GM", "name": "General Motors Company"},
    {"code": "GOOG", "name": "Alphabet Inc. (Class C)"},
    {"code": "GOOGL", "name": "Alphabet Inc. (Class A)"},
    {"code": "GPN", "name": "Global Payments Inc."},
    {"code": "GRMN", "name": "Garmin Ltd."},
    {"code": "GS", "name": "The Goldman Sachs Group, Inc."},
    {"code": "HAL", "name": "Halliburton Company"},
    {"code": "HAS", "name": "Hasbro, Inc."},
    {"code": "HBAN", "name": "Huntington Bancshares Incorporated"},
    {"code": "HD", "name": "The Home Depot, Inc."},
    {"code": "HES", "name": "Hess Corporation"},
    {"code": "HII", "name": "Huntington Ingalls Industries, Inc."},
    {"code": "HLT", "name": "Hilton Worldwide Holdings Inc."},
    {"code": "HPE", "name": "Hewlett Packard Enterprise Company"},
    {"code": "HPQ", "name": "HP Inc."},
    {"code": "HUM", "name": "Humana Inc."},
    {"code": "IBM", "name": "International Business Machines Corporation"},
    {"code": "ICE", "name": "Intercontinental Exchange, Inc."},
    {"code": "IDXX", "name": "IDEXX Laboratories, Inc."},
    {"code": "IEX", "name": "IDEX Corporation"},
    {"code": "IFF", "name": "International Flavors & Fragrances Inc."},
    {"code": "INTC", "name": "Intel Corporation"},
    {"code": "INTU", "name": "Intuit Inc."},
    {"code": "IP", "name": "International Paper Company"},
    {"code": "IPG", "name": "The Interpublic Group of Companies, Inc."},
    {"code": "IR", "name": "Ingersoll Rand Inc."},
    {"code": "J", "name": "Jacobs Solutions Inc."},
    {"code": "JBL", "name": "Jabil Inc."},
    {"code": "JCI", "name": "Johnson Controls International plc"},
    {"code": "JEF", "name": "Jefferies Financial Group Inc."},
    {"code": "JKHY", "name": "Jack Henry & Associates, Inc."},
    {"code": "JNJ", "name": "Johnson & Johnson"},
    {"code": "JNPR", "name": "Juniper Networks, Inc."},
    {"code": "JPM", "name": "JPMorgan Chase & Co."},
    {"code": "K", "name": "Kellanova"},
    {"code": "KEY", "name": "KeyCorp"},
    {"code": "KEYS", "name": "Keysight Technologies, Inc."},
    {"code": "KHC", "name": "The Kraft Heinz Company"},
    {"code": "KIM", "name": "Kimco Realty Corporation"},
    {"code": "KLAC", "name": "KLA Corporation"},
    {"code": "KO", "name": "The Coca-Cola Company"},
    {"code": "KR", "name": "The Kroger Co."},
    {"code": "L", "name": "Loews Corporation"},
    {"code": "LDOS", "name": "Leidos Holdings, Inc."},
    {"code": "LEN", "name": "Lennar Corporation"},
    {"code": "LH", "name": "Labcorp"},
    {"code": "LHX", "name": "L3Harris Technologies, Inc."},
    {"code": "LIN", "name": "Linde plc"},
    {"code": "LLY", "name": "Eli Lilly and Company"},
    {"code": "LMT", "name": "Lockheed Martin Corporation"},
    {"code": "LOW", "name": "Lowe's Companies, Inc."},
    {"code": "LRCX", "name": "Lam Research Corporation"},
    {"code": "LULU", "name": "Lululemon Athletica Inc."},
    {"code": "M", "name": "Macy's, Inc. (Historical)"},
    {"code": "MA", "name": "Mastercard Incorporated"},
    {"code": "MCD", "name": "McDonald's Corporation"},
    {"code": "MCK", "name": "McKesson Corporation"},
    {"code": "MCO", "name": "Moody's Corporation"},
    {"code": "MDLZ", "name": "Mondelez International, Inc."},
    {"code": "MDT", "name": "Medtronic plc"},
    {"code": "MET", "name": "MetLife, Inc."},
    {"code": "META", "name": "Meta Platforms, Inc."},
    {"code": "MGM", "name": "MGM Resorts International"},
    {"code": "MKC", "name": "McCormick & Company, Incorporated"},
    {"code": "MMC", "name": "Marsh & McLennan Companies, Inc."},
    {"code": "MMM", "name": "3M Company"},
    {"code": "MNST", "name": "Monster Beverage Corporation"},
    {"code": "MO", "name": "Altria Group, Inc."},
    {"code": "MRK", "name": "Merck & Co., Inc."},
    {"code": "MRO", "name": "Marathon Oil Corporation"},
    {"code": "MSFT", "name": "Microsoft Corporation"},
    {"code": "MSI", "name": "Motorola Solutions, Inc."},
    {"code": "MTD", "name": "Mettler-Toledo International Inc."},
    {"code": "MU", "name": "Micron Technology, Inc."},
    {"code": "NKE", "name": "NIKE, Inc."},
    {"code": "NOC", "name": "Northrop Grumman Corporation"},
    {"code": "NOW", "name": "ServiceNow, Inc."},
    {"code": "NRG", "name": "NRG Energy, Inc."},
    {"code": "NSC", "name": "Norfolk Southern Corporation"},
    {"code": "NVDA", "name": "NVIDIA Corporation"},
    {"code": "NVR", "name": "NVR, Inc."},
    {"code": "ODFL", "name": "Old Dominion Freight Line, Inc."},
    {"code": "OKE", "name": "ONEOK, Inc."},
    {"code": "OMC", "name": "Omnicom Group Inc."},
    {"code": "ORCL", "name": "Oracle Corporation"},
    {"code": "OXY", "name": "Occidental Petroleum Corporation"},
    {"code": "PAGS", "name": "PagSeguro Digital Ltd."},
    {"code": "PCAR", "name": "PACCAR Inc"},
    {"code": "PEAK", "name": "Healthpeak Properties, Inc."},
    {"code": "PEG", "name": "Public Service Enterprise Group Incorporated"},
    {"code": "PEP", "name": "PepsiCo, Inc."},
    {"code": "PFE", "name": "Pfizer Inc."},
    {"code": "PG", "name": "The Procter & Gamble Company"},
    {"code": "PGR", "name": "The Progressive Corporation"},
    {"code": "PH", "name": "Parker-Hannifin Corporation"},
    {"code": "PHM", "name": "PulteGroup, Inc."},
    {"code": "PKG", "name": "Packaging Corporation of America"},
    {"code": "PLD", "name": "Prologis, Inc."},
    {"code": "PM", "name": "Philip Morris International Inc."},
    {"code": "PNC", "name": "PNC Financial Services Group, Inc."},
    {"code": "PNR", "name": "Pentair plc"},
    {"code": "PNW", "name": "Pinnacle West Capital Corporation"},
    {"code": "PPG", "name": "PPG Industries, Inc."},
    {"code": "PPL", "name": "PPL Corporation"},
    {"code": "PRU", "name": "Prudential Financial, Inc."},
    {"code": "PSA", "name": "Public Storage"},
    {"code": "PSX", "name": "Phillips 66"},
    {"code": "PTC", "name": "PTC Inc."},
    {"code": "PVH", "name": "PVH Corp."},
    {"code": "PWR", "name": "Quanta Services, Inc."},
    {"code": "PYPL", "name": "PayPal Holdings, Inc."},
    {"code": "QCOM", "name": "QUALCOMM Incorporated"},
    {"code": "RCL", "name": "Royal Caribbean Group"},
    {"code": "REGN", "name": "Regeneron Pharmaceuticals, Inc."},
    {"code": "RF", "name": "Regions Financial Corporation"},
    {"code": "RHI", "name": "Robert Half International Inc."},
    {"code": "RJF", "name": "Raymond James Financial, Inc."},
    {"code": "RL", "name": "Ralph Lauren Corporation"},
    {"code": "ROK", "name": "Rockwell Automation, Inc."},
    {"code": "ROL", "name": "Rollins, Inc."},
    {"code": "ROP", "name": "Roper Technologies, Inc."},
    {"code": "RSG", "name": "Republic Services, Inc."},
    {"code": "RTX", "name": "RTX Corporation"},
    {"code": "SBUX", "name": "Starbucks Corporation"},
    {"code": "SCHW", "name": "The Charles Schwab Corporation"},
    {"code": "SE", "name": "Sea Limited (Historical)"},
    {"code": "SEE", "name": "Sealed Air Corporation"},
    {"code": "SJM", "name": "The J. M. Smucker Company"},
    {"code": "SLB", "name": "Schlumberger Limited"},
    {"code": "SMCI", "name": "Super Micro Computer, Inc."},
    {"code": "SPG", "name": "Simon Property Group, Inc."},
    {"code": "SRE", "name": "Sempra"},
    {"code": "STE", "name": "Steris plc"},
    {"code": "STX", "name": "Seagate Technology Holdings plc"},
    {"code": "STZ", "name": "Constellation Brands, Inc."},
    {"code": "SWK", "name": "Stanley Black & Decker, Inc."},
    {"code": "SYK", "name": "Stryker Corporation"},
    {"code": "T", "name": "AT&T Inc."},
    {"code": "TAP", "name": "Molson Coors Beverage Company"},
    {"code": "TGT", "name": "Target Corporation"},
    {"code": "TJX", "name": "The TJX Companies, Inc."},
    {"code": "TMUS", "name": "T-Mobile US, Inc."},
    {"code": "TSLA", "name": "Tesla, Inc."},
    {"code": "TXN", "name": "Texas Instruments Incorporated"},
    {"code": "TXT", "name": "Textron Inc."},
    {"code": "UDR", "name": "UDR, Inc."},
    {"code": "ULTA", "name": "Ulta Beauty, Inc."},
    {"code": "UNH", "name": "UnitedHealth Group Incorporated"},
    {"code": "UPS", "name": "United Parcel Service, Inc."},
    {"code": "V", "name": "Visa Inc. (Class A)"},
    {"code": "VFC", "name": "V.F. Corporation"},
    {"code": "VRSK", "name": "Verisk Analytics, Inc."},
    {"code": "VRTX", "name": "Vertex Pharmaceuticals Incorporated"},
    {"code": "VZ", "name": "Verizon Communications Inc."},
    {"code": "WBA", "name": "Walgreens Boots Alliance, Inc."},
    {"code": "WEC", "name": "WEC Energy Group, Inc."},
    {"code": "WELL", "name": "Welltower Inc."},
    {"code": "WFC", "name": "Wells Fargo & Company"},
    {"code": "WHR", "name": "Whirlpool Corporation"},
    {"code": "WLTW", "name": "Willis Towers Watson Public Limited Company (Historical)"},
    {"code": "WMB", "name": "The Williams Companies, Inc."},
    {"code": "WMT", "name": "Walmart Inc."},
    {"code": "WY", "name": "Weyerhaeuser Company"},
    {"code": "XOM", "name": "Exxon Mobil Corporation"},
    {"code": "YUM", "name": "Yum! Brands, Inc."},
    {"code": "ZBH", "name": "Zimmer Biomet Holdings, Inc."},
    {"code": "ZTS", "name": "Zoetis Inc."},
]



#日経２２５リスト
nikkei225_list = [
    # 医薬品
    {"code": "4151.T", "name": "協和キリン"},
    {"code": "4502.T", "name": "武田薬品工業"},
    {"code": "4503.T", "name": "アステラス製薬"},
    {"code": "4506.T", "name": "住友ファーマ"},
    {"code": "4507.T", "name": "塩野義製薬"},
    {"code": "4519.T", "name": "中外製薬"},
    {"code": "4523.T", "name": "エーザイ"},
    {"code": "4568.T", "name": "第一三共"},
    {"code": "4578.T", "name": "大塚ホールディングス"},

    # 電気機器
    {"code": "4062.T", "name": "イビデン"},
    {"code": "6479.T", "name": "ミネベアミツミ"},
    {"code": "6501.T", "name": "日立製作所"},
    {"code": "6503.T", "name": "三菱電機"},
    {"code": "6504.T", "name": "富士電機"},
    {"code": "6506.T", "name": "安川電機"},
    {"code": "6526.T", "name": "ソシオネクスト"},
    {"code": "6645.T", "name": "オムロン"},
    {"code": "6674.T", "name": "GSユアサ"},
    {"code": "6701.T", "name": "NEC"},
    {"code": "6702.T", "name": "富士通"},
    {"code": "6723.T", "name": "ルネサス"},
    {"code": "6724.T", "name": "セイコーエプソン"},
    {"code": "6752.T", "name": "パナソニックHD"},
    {"code": "6753.T", "name": "シャープ"},
    {"code": "6758.T", "name": "ソニーグループ"},
    {"code": "6762.T", "name": "TDK"},
    {"code": "6770.T", "name": "アルプスアルパイン"},
    {"code": "6841.T", "name": "横河電機"},
    {"code": "6857.T", "name": "アドバンテスト"},
    {"code": "6861.T", "name": "キーエンス"},
    {"code": "6902.T", "name": "デンソー"},
    {"code": "6920.T", "name": "レーザーテック"},
    {"code": "6952.T", "name": "カシオ計算機"},
    {"code": "6954.T", "name": "ファナック"},
    {"code": "6963.T", "name": "ローム"},
    {"code": "6971.T", "name": "京セラ"},
    {"code": "6976.T", "name": "太陽誘電"},
    {"code": "6981.T", "name": "村田製作所"},
    {"code": "7735.T", "name": "SCREEN HD"},
    {"code": "7751.T", "name": "キヤノン"},
    {"code": "7752.T", "name": "リコー"},
    {"code": "8035.T", "name": "東京エレクトロン"},

    # 自動車
    {"code": "7201.T", "name": "日産自動車"},
    {"code": "7202.T", "name": "いすゞ自動車"},
    {"code": "7203.T", "name": "トヨタ自動車"},
    {"code": "7205.T", "name": "日野自動車"},
    {"code": "7211.T", "name": "三菱自動車"},
    {"code": "7261.T", "name": "マツダ"},
    {"code": "7267.T", "name": "ホンダ"},
    {"code": "7269.T", "name": "スズキ"},
    {"code": "7270.T", "name": "SUBARU"},
    {"code": "7272.T", "name": "ヤマハ発動機"},

    # 精密機器
    {"code": "4543.T", "name": "テルモ"},
    {"code": "4902.T", "name": "コニカミノルタ"},
    {"code": "6146.T", "name": "ディスコ"},
    {"code": "7731.T", "name": "ニコン"},
    {"code": "7733.T", "name": "オリンパス"},
    {"code": "7741.T", "name": "HOYA"},

    # 通信
    {"code": "9432.T", "name": "NTT"},
    {"code": "9433.T", "name": "KDDI"},
    {"code": "9434.T", "name": "ソフトバンク"},
    {"code": "9984.T", "name": "ソフトバンクグループ"},

    # 銀行
    {"code": "5831.T", "name": "しずおかFG"},
    {"code": "7186.T", "name": "横浜FG"},
    {"code": "8304.T", "name": "あおぞら銀行"},
    {"code": "8306.T", "name": "三菱UFJ"},
    {"code": "8308.T", "name": "りそなHD"},
    {"code": "8309.T", "name": "三井住友トラスト"},
    {"code": "8316.T", "name": "三井住友FG"},
    {"code": "8331.T", "name": "千葉銀行"},
    {"code": "8354.T", "name": "ふくおかFG"},
    {"code": "8411.T", "name": "みずほFG"},

    # その他金融
    {"code": "8253.T", "name": "クレディセゾン"},
    {"code": "8591.T", "name": "オリックス"},
    {"code": "8697.T", "name": "日本取引所"},

    # 証券
    {"code": "8601.T", "name": "大和証券G"},
    {"code": "8604.T", "name": "野村HD"},

    # 保険
    {"code": "8630.T", "name": "SOMPO"},
    {"code": "8725.T", "name": "MS&AD"},
    {"code": "8750.T", "name": "第一生命HD"},
    {"code": "8766.T", "name": "東京海上HD"},
    {"code": "8795.T", "name": "T&D HD"},

    # 水産
    {"code": "1332.T", "name": "ニッスイ"},

    # 食品
    {"code": "2002.T", "name": "日清製粉G"},
    {"code": "2269.T", "name": "明治HD"},
    {"code": "2282.T", "name": "日本ハム"},
    {"code": "2501.T", "name": "サッポロHD"},
    {"code": "2502.T", "name": "アサヒGHD"},
    {"code": "2503.T", "name": "キリンHD"},
    {"code": "2801.T", "name": "キッコーマン"},
    {"code": "2802.T", "name": "味の素"},
    {"code": "2871.T", "name": "ニチレイ"},
    {"code": "2914.T", "name": "JT"},

    # 小売り
    {"code": "3086.T", "name": "Jフロント"},
    {"code": "3092.T", "name": "ZOZO"},
    {"code": "3099.T", "name": "三越伊勢丹HD"},
    {"code": "3382.T", "name": "セブン＆アイHD"},
    {"code": "7453.T", "name": "良品計画"},
    {"code": "8233.T", "name": "高島屋"},
    {"code": "8252.T", "name": "丸井G"},
    {"code": "8267.T", "name": "イオン"},
    {"code": "9843.T", "name": "ニトリHD"},
    {"code": "9983.T", "name": "ファーストリテイリング"},

    # サービス
    {"code": "2413.T", "name": "エムスリー"},
    {"code": "2432.T", "name": "ディーエヌエー"},
    {"code": "3659.T", "name": "ネクソン"},
    {"code": "3697.T", "name": "SHIFT"},
    {"code": "4307.T", "name": "野村総研"},
    {"code": "4324.T", "name": "電通グループ"},
    {"code": "4385.T", "name": "メルカリ"},
    {"code": "4661.T", "name": "オリエンタルランド"},
    {"code": "4689.T", "name": "LINEヤフー"},
    {"code": "4704.T", "name": "トレンドマイクロ"},
    {"code": "4751.T", "name": "サイバーエージェント"},
    {"code": "4755.T", "name": "楽天グループ"},
    {"code": "6098.T", "name": "リクルートHD"},
    {"code": "6178.T", "name": "日本郵政"},
    {"code": "6532.T", "name": "ベイカレント"},
    {"code": "7974.T", "name": "任天堂"},
    {"code": "9602.T", "name": "東宝"},
    {"code": "9735.T", "name": "セコム"},
    {"code": "9766.T", "name": "コナミG"},

    # 鉱業
    {"code": "1605.T", "name": "INPEX"},

    # 繊維
    {"code": "3401.T", "name": "帝人"},
    {"code": "3402.T", "name": "東レ"},

    # パルプ・紙
    {"code": "3861.T", "name": "王子HD"},

    # 化学
    {"code": "3405.T", "name": "クラレ"},
    {"code": "3407.T", "name": "旭化成"},
    {"code": "4004.T", "name": "レゾナックHD"},
    {"code": "4005.T", "name": "住友化学"},
    {"code": "4021.T", "name": "日産化学"},
    {"code": "4042.T", "name": "東ソー"},
    {"code": "4043.T", "name": "トクヤマ"},
    {"code": "4061.T", "name": "デンカ"},
    {"code": "4063.T", "name": "信越化学工業"},
    {"code": "4183.T", "name": "三井化学"},
    {"code": "4188.T", "name": "三菱ケミカルG"},
    {"code": "4208.T", "name": "UBE"},
    {"code": "4452.T", "name": "花王"},
    {"code": "4901.T", "name": "富士フイルム"},
    {"code": "4911.T", "name": "資生堂"},
    {"code": "6988.T", "name": "日東電工"},

    # 石油
    {"code": "5019.T", "name": "出光興産"},
    {"code": "5020.T", "name": "ENEOS"},

    # ゴム
    {"code": "5101.T", "name": "横浜ゴム"},
    {"code": "5108.T", "name": "ブリヂストン"},

    # 窯業
    {"code": "5201.T", "name": "AGC"},
    {"code": "5214.T", "name": "日本電気硝子"},
    {"code": "5233.T", "name": "太平洋セメント"},

    # 鉄鋼
    {"code": "5301.T", "name": "東海カーボン"},
    {"code": "5332.T", "name": "TOTO"},
    {"code": "5333.T", "name": "日本碍子"},
    {"code": "5401.T", "name": "日本製鉄"},
    {"code": "5406.T", "name": "神戸製鋼所"},
    {"code": "5411.T", "name": "JFE HD"},

    # 非鉄金属
    {"code": "3436.T", "name": "SUMCO"},
    {"code": "5706.T", "name": "三井金属"},
    {"code": "5711.T", "name": "三菱マテリアル"},
    {"code": "5713.T", "name": "住友金属鉱山"},
    {"code": "5714.T", "name": "DOWA"},
    {"code": "5801.T", "name": "古河電工"},
    {"code": "5802.T", "name": "住友電工"},
    {"code": "5803.T", "name": "フジクラ"},

    # 商社
    {"code": "2768.T", "name": "双日"},
    {"code": "8001.T", "name": "伊藤忠商事"},
    {"code": "8002.T", "name": "丸紅"},
    {"code": "8015.T", "name": "豊田通商"},
    {"code": "8031.T", "name": "三井物産"},
    {"code": "8053.T", "name": "住友商事"},
    {"code": "8058.T", "name": "三菱商事"},

    # 建設
    {"code": "1721.T", "name": "コムシスHD"},
    {"code": "1801.T", "name": "大成建設"},
    {"code": "1802.T", "name": "大林組"},
    {"code": "1803.T", "name": "清水建設"},
    {"code": "1808.T", "name": "長谷工"},
    {"code": "1812.T", "name": "鹿島建設"},
    {"code": "1925.T", "name": "大和ハウス工業"},
    {"code": "1928.T", "name": "積水ハウス"},
    {"code": "1963.T", "name": "日揮HD"},

    # 機械
    {"code": "5631.T", "name": "日本製鋼所"},
    {"code": "6103.T", "name": "オークマ"},
    {"code": "6113.T", "name": "アマダ"},
    {"code": "6273.T", "name": "SMC"},
    {"code": "6301.T", "name": "コマツ"},
    {"code": "6302.T", "name": "住友重機"},
    {"code": "6305.T", "name": "日立建機"},
    {"code": "6326.T", "name": "クボタ"},
    {"code": "6361.T", "name": "荏原製作所"},
    {"code": "6367.T", "name": "ダイキン工業"},
    {"code": "6471.T", "name": "日本精工"},
    {"code": "6472.T", "name": "NTN"},
    {"code": "6473.T", "name": "ジェイテクト"},
    {"code": "7004.T", "name": "カナデビア"},
    {"code": "7011.T", "name": "三菱重工業"},
    {"code": "7013.T", "name": "IHI"},

    # 造船
    {"code": "7012.T", "name": "川崎重工業"},

    # その他製造
    {"code": "7832.T", "name": "バンダイナムコHD"},
    {"code": "7911.T", "name": "TOPPAN"},
    {"code": "7912.T", "name": "大日本印刷"},
    {"code": "7951.T", "name": "ヤマハ"},

    # 不動産
    {"code": "3289.T", "name": "東急不HD"},
    {"code": "8801.T", "name": "三井不動産"},
    {"code": "8802.T", "name": "三菱地所"},
    {"code": "8804.T", "name": "東京建物"},
    {"code": "8830.T", "name": "住友不動産"},

    # 鉄道・バス
    {"code": "9001.T", "name": "東武鉄道"},
    {"code": "9005.T", "name": "東急"},
    {"code": "9007.T", "name": "小田急電鉄"},
    {"code": "9008.T", "name": "京王電鉄"},
    {"code": "9009.T", "name": "京成電鉄"},
    {"code": "9020.T", "name": "JR東日本"},
    {"code": "9021.T", "name": "JR西日本"},
    {"code": "9022.T", "name": "JR東海"},

    # 陸運
    {"code": "9064.T", "name": "ヤマトHD"},
    {"code": "9147.T", "name": "NXHD"},

    # 海運
    {"code": "9101.T", "name": "日本郵船"},
    {"code": "9104.T", "name": "商船三井"},
    {"code": "9107.T", "name": "川崎汽船"},

    # 空運
    {"code": "9201.T", "name": "JAL"},
    {"code": "9202.T", "name": "ANA HD"},

    # 電力
    {"code": "9501.T", "name": "東京電力HD"},
    {"code": "9502.T", "name": "中部電力"},
    {"code": "9503.T", "name": "関西電力"},

    # ガス
    {"code": "9531.T", "name": "東京ガス"},
    {"code": "9532.T", "name": "大阪ガス"},
]
